### ISSUE TITLE
.yml export for IYPT-compatibility reasons

### ISSUE THREAD

**Issue by nickkolok** [vbonvin/ipt_connect#299]
Here is an example of the file provided by Klim Sladkov. Looks rather easy to implement - both via Django templates or via a library for generating `yml`.
```
- - room: A
    stages:
    - presented: 1
      rejected:
      - 6
      teams:
        Opponent:
          grades:
          - - Matej Badin
            - 5
          - - Kent Hogan
            - 6
          - - Teck Seng Koh
            - 5
          - - Shashikant Pandey
            - 6
          - - Radost Waszkiewicz
            - 6
          person: Andrey Shusharin
          team: Russia
        Reporter:
          grades:
          - - Matej Badin
            - 3
          - - Kent Hogan
            - 3
          - - Teck Seng Koh
            - 3
          - - Shashikant Pandey
            - 4
          - - Radost Waszkiewicz
            - 3
          person: Christos Anastasios Bovolis
          team: Greece
        Reviewer:
          grades:
          - - Matej Badin
            - 8
          - - Kent Hogan
            - 7
          - - Teck Seng Koh
            - 6
          - - Shashikant Pandey
            - 8
          - - Radost Waszkiewicz
            - 10
          person: Hanyue Wang
          team: China
    - presented: 6
      rejected: []
      teams:
        Opponent:
          grades:
          - - Matej Badin
            - 5
          - - Kent Hogan
            - 6
          - - Teck Seng Koh
            - 6
          - - Shashikant Pandey
            - 5
          - - Radost Waszkiewicz
            - 3
          person: Guanyu Zhu
          team: China
        Reporter:
          grades:
          - - Matej Badin
            - 5
          - - Kent Hogan
            - 5
          - - Teck Seng Koh
            - 5
          - - Shashikant Pandey
            - 5
          - - Radost Waszkiewicz
            - 4
          person: Andrey Shusharin
          team: Russia
        Reviewer:
          grades:
          - - Matej Badin
            - 7
          - - Kent Hogan
            - 5
          - - Teck Seng Koh
            - 6
          - - Shashikant Pandey
            - 6
          - - Radost Waszkiewicz
            - 5
          person: Negar Rahimi
          team: Iran
    - presented: 4
      rejected: []
      teams:
        Opponent:
          grades:
          - - Matej Badin
            - 4
          - - Kent Hogan
            - 5
          - - Teck Seng Koh
            - 4
          - - Shashikant Pandey
            - 5
          - - Radost Waszkiewicz
            - 5
          person: Rojan Abdollahzade
          team: Iran
        Reporter:
          grades:
          - - Matej Badin
            - 6
          - - Kent Hogan
            - 6
          - - Teck Seng Koh
            - 6
          - - Shashikant Pandey
            - 7
          - - Radost Waszkiewicz
            - 6
          person: Hanyue Wang
          team: China
        Reviewer:
          grades:
          - - Matej Badin
            - 5
          - - Kent Hogan
            - 7
          - - Teck Seng Koh
            - 3
          - - Shashikant Pandey
            - 4
          - - Radost Waszkiewicz
            - 3
          person: Hennes Philip Alt
          team: Greece
    - presented: 14
      rejected:
      - 2
      - 12
      teams:
        Opponent:
          grades:
          - - Matej Badin
            - 3
          - - Kent Hogan
            - 4
          - - Teck Seng Koh
            - 4
          - - Shashikant Pandey
            - 4
          - - Radost Waszkiewicz
            - 3
          person: Vasileios Kachtsidis
          team: Greece
        Reporter:
          grades:
          - - Matej Badin
            - 6
          - - Kent Hogan
            - 7
          - - Teck Seng Koh
            - 6
          - - Shashikant Pandey
            - 6
          - - Radost Waszkiewicz
            - 8
          person: Rojan Abdollahzade
          team: Iran
        Reviewer:
          grades:
          - - Matej Badin
            - 7
          - - Kent Hogan
            - 8
          - - Teck Seng Koh
            - 8
          - - Shashikant Pandey
            - 8
          - - Radost Waszkiewicz
            - 9
          person: Ivan Polonik
          team: Russia
  - room: B
    stages:
    - presented: 14
      rejected: []
      teams:
        Opponent:
          grades:
          - - Tomas Opatrny
            - 7
          - - Alexander Merentsov
            - 6
          - - Susan Napier
            - 5
          - - Victor Paunescu
            - 5
          - - Chenghou Tu
            - 5
          person: Grgur Premec
          team: Croatia
        Reporter:
          grades:
          - - Tomas Opatrny
            - 5
          - - Alexander Merentsov
            - 3
          - - Susan Napier
            - 3
          - - Victor Paunescu
            - 4
          - - Chenghou Tu
            - 5
          person: Ijaz Ahmed
          team: Pakistan
        Reviewer:
          grades:
          - - Tomas Opatrny
            - 8
          - - Alexander Merentsov
            - 7
          - - Susan Napier
            - 7
          - - Victor Paunescu
            - 6
          - - Chenghou Tu
            - 6
          person: "Simon Sond\xE9n"
          team: Sweden
    - presented: 3
      rejected: []
      teams:
        Opponent:
          grades:
          - - Tomas Opatrny
            - 6
          - - Alexander Merentsov
            - 7
          - - Susan Napier
            - 6
          - - Victor Paunescu
            - 6
          - - Chenghou Tu
            - 6
          person: Sofia Danielson Damne
          team: Sweden
        Reporter:
          grades:
          - - Tomas Opatrny
            - 5
          - - Alexander Merentsov
            - 6
          - - Susan Napier
            - 4
          - - Victor Paunescu
            - 5
          - - Chenghou Tu
            - 5
          person: "Noa Jeli\u0107 Mato\u0161evi\u0107"
          team: Croatia
        Reviewer:
          grades:
          - - Tomas Opatrny
            - 5
          - - Alexander Merentsov
            - 5
          - - Susan Napier
            - 5
          - - Victor Paunescu
            - 6
          - - Chenghou Tu
            - 6
          person: Bilal Aslam
          team: Pakistan
    - presented: 1
      rejected:
      - 9
      teams:
        Opponent:
          grades:
          - - Tomas Opatrny
            - 4
          - - Alexander Merentsov
            - 5
          - - Susan Napier
            - 5
          - - Victor Paunescu
            - 6
          - - Chenghou Tu
            - 6
          person: Ijaz Ahmed
          team: Pakistan
        Reporter:
          grades:
          - - Tomas Opatrny
            - 5
          - - Alexander Merentsov
            - 5
          - - Susan Napier
            - 4
          - - Victor Paunescu
            - 5
          - - Chenghou Tu
            - 5
          person: Ale Loman
          team: Sweden
        Reviewer:
          grades:
          - - Tomas Opatrny
            - 7
          - - Alexander Merentsov
            - 5
          - - Susan Napier
            - 7
          - - Victor Paunescu
            - 7
          - - Chenghou Tu
            - 7
          person: Grgur Premec
          team: Croatia

      rejected: []
      teams:
        Opponent:
          grades:
          - - Kerry Parker
            - 6
          - - "Aleksandra Alori\u0107"
            - 5
          - - Elia Eschenazi
            - 6
          - - Igor Timoshchenko
            - 7
          - - Pornrat Wattanakasiwich
            - 6
          person: "Samuel J\xE1n Plesn\xEDk"
          team: Slovakia
        Reporter:
          grades:
          - - Kerry Parker
            - 4
          - - "Aleksandra Alori\u0107"
            - 5
          - - Elia Eschenazi
            - 5
          - - Igor Timoshchenko
            - 5
          - - Pornrat Wattanakasiwich
            - 5
          person: Praneel Chugh
          team: Australia
        Reviewer:
          grades:
          - - Kerry Parker
            - 6
          - - "Aleksandra Alori\u0107"
            - 8
          - - Elia Eschenazi
            - 8
          - - Igor Timoshchenko
            - 8
          - - Pornrat Wattanakasiwich
            - 9
          person: Frederik Gareis
          team: Germany
```
